### ISSUE TITLE
unrecognized command 'test'

### ISSUE THREAD

**Issue by Bogdanp** [jackfirth/racket-package-ci-action#1]
I tried using the action for [racket-redis](https://github.com/Bogdanp/racket-redis), but it seems it can't run the `raco test` command for some reason, despite the fact that I can see that `rackunit` was installed in the logs.

Ref: https://github.com/Bogdanp/racket-redis/commit/034fd976ce5a475ac0919ba7f3b5419e64029720/checks#step:5:49)

**Comment by jackfirth** [comment]
That's odd. For comparison, I'm using this action in my [Rebellion][rebellion] package and it builds and tests things just fine. Here's the [workflows.yml][workflows-config] config I'm using:

```yaml
name: CI

on: [push]

jobs:
  racket-package-ci:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v1
    - uses: jackfirth/racket-package-ci-action@v0.1.1
      with:
        name: rebellion
```

[rebellion]: https://github.com/jackfirth/rebellion
[workflows-config]: https://github.com/jackfirth/rebellion/blob/master/.github/workflows/main.yml
